import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ScanFinding {
  type: string;
  severity: string;
  message: string;
  details?: any;
}

export interface ScanResult {
  _id: string;
  url: string;
  status: string;
  riskScore: number;
  findings: ScanFinding[];
  createdAt: string;
}

export function generateVaptReport(scan: ScanResult) {
  const doc = new jsPDF();

  // Add Watermark/Logo placeholder
  doc.setFontSize(22);
  doc.setTextColor(0, 229, 255); // Cyan
  doc.text("VulnScanner", 14, 20);
  
  doc.setFontSize(16);
  doc.setTextColor(50, 50, 50);
  doc.text("Vulnerability Assessment & Penetration Testing Report", 14, 30);

  // Meta Information
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Target URL: ${scan.url}`, 14, 45);
  doc.text(`Scan ID: ${scan._id}`, 14, 52);
  doc.text(`Date: ${new Date(scan.createdAt).toLocaleString()}`, 14, 59);
  doc.text(`Risk Score: ${scan.riskScore}/100`, 14, 66);

  // Summary logic
  const critical = scan.findings.filter((f) => f.severity.toLowerCase() === "critical").length;
  const high = scan.findings.filter((f) => f.severity.toLowerCase() === "high").length;
  const medium = scan.findings.filter((f) => f.severity.toLowerCase() === "medium").length;
  const low = scan.findings.filter((f) => f.severity.toLowerCase() === "low").length;
  const info = scan.findings.filter((f) => f.severity.toLowerCase() === "info").length;

  doc.text(`Critical: ${critical} | High: ${high} | Medium: ${medium} | Low: ${low} | Info: ${info}`, 14, 73);

  // Findings Table
  const tableData = scan.findings.map((f) => [
    f.severity.toUpperCase(),
    f.type.toUpperCase().replace(/_/g, " "),
    f.message,
  ]);

  autoTable(doc, {
    startY: 85,
    head: [["Severity", "Type", "Description"]],
    body: tableData,
    theme: "grid",
    headStyles: { fillColor: [0, 120, 150] },
    willDrawCell: (data) => {
      // Color-code severities
      if (data.section === "body" && data.column.index === 0) {
        const severity = data.cell.raw as string;
        if (severity === "CRITICAL") {
          data.cell.styles.textColor = [220, 38, 38]; // Red
          data.cell.styles.fontStyle = "bold";
        } else if (severity === "HIGH") {
          data.cell.styles.textColor = [234, 88, 12]; // Orange
        } else if (severity === "MEDIUM") {
          data.cell.styles.textColor = [202, 138, 4]; // Yellow
        } else if (severity === "LOW") {
          data.cell.styles.textColor = [59, 130, 246]; // Blue
        } else {
          data.cell.styles.textColor = [34, 197, 94]; // Green
        }
      }
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by VulnScanner DevSecOps Platform`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  // Download
  doc.save(`VAPT_Report_${scan.url.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf`);
}
